# Generated by Django 4.2.6 on 2023-10-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albom',
            name='rasm',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='qoshiq',
            name='davomiylik',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qoshiq',
            name='fayl',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
