# Generated by Django 4.2.6 on 2023-10-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyApp', '0003_izoh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='izoh',
            old_name='kino',
            new_name='qoshiq',
        ),
    ]
