# Generated by Django 4.2.6 on 2023-10-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyApp', '0004_rename_kino_izoh_qoshiq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='izoh',
            name='qoshiq',
        ),
        migrations.AddField(
            model_name='izoh',
            name='albom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiyApp.albom'),
        ),
    ]
